/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BingoRouteImport } from './routes/bingo'
import { Route as IndexRouteImport } from './routes/index'

const BingoRoute = BingoRouteImport.update({
  id: '/bingo',
  path: '/bingo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bingo': typeof BingoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bingo': typeof BingoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bingo': typeof BingoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bingo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bingo'
  id: '__root__' | '/' | '/bingo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BingoRoute: typeof BingoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/bingo': {
      id: '/bingo'
      path: '/bingo'
      fullPath: '/bingo'
      preLoaderRoute: typeof BingoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BingoRoute: BingoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
